apiVersion: v1
kind: Pod
metadata:
  name: online-inference-probes
  labels:
    app: online-inference
spec:  
  containers:
    - name: online-inference
      image: tinctura/ml_app:v8
      imagePullPolicy: "Always"
      ports:
        - containerPort: 8088
      readinessProbe:
        tcpSocket:
          port: 8088
        initialDelaySeconds: 5
        periodSeconds: 5
        failureThreshold: 5
      livenessProbe:
        httpGet:
          path: /health
          port: 8088
        initialDelaySeconds: 5
        periodSeconds: 60
        failureThreshold: 1