# data
input_data_path: "data/raw/heart_cleveland.csv"
output_model_path: "models/model.pkl"
output_transformer_path: "models/transformer.pkl"
metric_path: "models/metrics.json"
report_path: "reports/EDA_pandas_profiling.html"

# features
categorical_features:
  - "sex"
  - "cp"
  - "fbs"
  - "restecg"
  - "exang"
  - "slope"
  - "ca"
  - "thal"
numerical_features:
  - "age"
  - "trestbps"
  - "chol"
  - "thalach"
  - "oldpeak"
target_column: "target"

# split
val_size: 0.2
random_state: 118

# models
defaults:
  - model: lr